### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by einarf** [jonwright/pyopengltk#5] opened 2019-10-10 13:32 UTC
Just got very confused:
* This repo has one tagged release : https://github.com/jonwright/pyopengltk/releases
* The current `setup.py` version says `0.0.1`
* BUT .. there is also a `0.0.2` on PyPI : https://pypi.org/project/pyopengltk/#history

I have not tried `0.0.2` yet. I used the version from the current master blindly. I assume it possibly contains a bug fix if semantic versioning is used.

**Comment by einarf** [comment] 2019-10-10 16:19
Just tried 0.0.2 in moderngl-window and it was working fine. Assuming it contains some improvement.

**Comment by jonwright** [comment] 2019-10-14 10:13
I went to 0.0.3.
It will fall over on windows due to a problem in pyopengl 3.1.3b2 if that is pip installed (_check_size missing in WGL, fixed in bzr head apparently).

**Comment by einarf** [comment] 2019-10-14 12:59
Looks great on PyPI and the package is working :+1: 

I get `PyOpenGL==3.1.0` installed from the dependency in setup.py. Do you get `3.1.3b2` installed?

**Comment by jonwright** [comment] 2019-10-14 14:08
On a clean environment I seem to reproducibly get 3.1.0 using pip. 
I do not understand how 3.1.3b2 showed up. Perhaps it came from conda? 
Anyway, the problem I hit reproduces with either: 
   `conda install pyopengl` 
or with
   `pip install pyopengl --pre`

```
(testpyopengltk) C:\Users\wright>pip install pyopengltk
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pyopengltk
  Using cached https://files.pythonhosted.org/packages/3f/7d/2d1b9393d7f1a5f9c3fd676ff5a606efeea772dbb872f3e93716d9fb4ce4/pyopengltk-0.0.3-py2.py3-none-any.whl
Requirement already satisfied: pyopengl in c:\miniconda3\envs\testpyopengltk\lib\site-packages (from pyopengltk) (3.1.3b2)
Installing collected packages: pyopengltk
Successfully installed pyopengltk-0.0.3

(testpyopengltk) C:\Users\wright>python -c "import pyopengltk"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\pyopengltk\__init__.py", line 27, in <module>
    from pyopengltk.win32 import OpenGLFrame
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\pyopengltk\win32.py", line 6, in <module>
    from OpenGL.WGL import PIXELFORMATDESCRIPTOR, ChoosePixelFormat, \
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\WGL\__init__.py", line 1, in <module>
    from OpenGL.raw.WGL.VERSION.WGL_1_0 import *
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\raw\WGL\VERSION\WGL_1_0.py", line 4, in <module>
    from OpenGL.raw.WGL import _types as _cs
  File "c:\miniconda3\envs\testpyopengltk\lib\site-packages\OpenGL\raw\WGL\_types.py", line 85, in <module>
    _check_size(HANDLE)
NameError: name '_check_size' is not defined
```

**Comment by jonwright** [comment] 2019-10-14 14:11
So I transfer that to a new issue and close this one until we get a new version...

**Closed as completed by jonwright** 2019-10-14 14:11 UTC
